### ISSUE TITLE
Nothing happens when next page tester is run with jest

### ISSUE THREAD

**Issue by dbehmoaras** [next-page-tester/next-page-tester#293] opened 2022-02-15 16:35 UTC
Hello,

I'm trying to use next-page-tester to test if a page has rendered. When I run the test with jest, it indicates that the test is running, then exits. No error code, no logs, nothing. It just exits and ignores any other test in that file. I'm expecting the test to run, but it does not.

NextJS 12.0.10
Jest 27.3.1

```js
//index.page.tsx
import type { NextPage } from 'next';
export const Home: NextPage = () => {
  return(<div>Home page</div>
}

//index.page.spec.tsx
import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { getPage } from 'next-page-tester';

describe('GIVEN the home page', () => {
  it('THEN renders Home page text on the screen', async () => {
   
    const { render } = await getPage({
      route: '/'
    });
    render();
    expect(screen.getByText('Home page')).toBeVisible();

  //I added this test to try and debug (this test should obviously fail, but still nothing:
    expect(1).toEqual(2);
  })
})

**Comment by kouliavtsev** [comment] 2022-02-23 12:39
@dbehmoaras 

Could it be that Jest is not finding the folder with your test? 

Try to change `"test": "jest --watch"` to `"test": "jest --watchAll"`

**Comment by dbehmoaras** [comment] 2022-03-01 12:48
@kouliavtsev 

Thanks for the reply (sorry for my delay, I was travelling the last few days).

I can confirm that jest is finding the folder with my test since the console actually shows the file being tested (ie: TESTS - followed by the describe block being tested with the string that I passed in). Moreover, if I remove the test that uses the next-page-tester and instead add in a placeholder assertion, the test runs that assertion.

Additionally, to make sure that this wasn't the case, I also tried manually running that specific test file directly in the command line, but I get the same result: TESTS - Given the home page, and then the test just stops.

**Comment by dbehmoaras** [comment] 2022-03-11 15:50
Hoping that the PR that was just merged will address this

**Comment by newtmex** [comment] 2022-03-23 03:44
Have you checked if the issue is from `next-page-tester`? Try removing all `next-page-tester` and `@testing-library/react`, then try a simple test (like this one: `expect(1).toEqual(2);`) and see if the test file will run as expected.

**Comment by dbehmoaras** [comment] 2022-03-23 12:52
> Have you checked if the issue is from `next-page-tester`? Try removing all `next-page-tester` and `@testing-library/react`, then try a simple test (like this one: `expect(1).toEqual(2);`) and see if the test file will run as expected.

I am 100% sure that the issue is with next-page-tester. I have tried all kinds of permutations when running this test file, and this behavior only occurs when I add the following:
```js
const { render } = await getPage({
  route: '/'
});
render();
```

**Comment by toomuchdesign** [comment] 2022-04-06 09:55
Closing since no repro was provided. Feel free to open a new issue with a repro in case the issue persists.

**Closed by toomuchdesign** 2022-04-06 09:55 UTC
Labels: needs-repro
