### ISSUE TITLE
error Command failed with signal "SIGSEGV".

### ISSUE THREAD

**Issue by railsfactory-sivamanikandan** [next-page-tester/next-page-tester#292] opened 2022-01-10 11:12 UTC
error Command failed with signal "SIGSEGV".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by RichMatthews** [comment] 2022-01-20 11:10
I'm also getting this issue

**Comment by tylerzey** [comment] 2022-01-26 20:09
Any idea what might be causing this? I'm also getting this issue.

**Comment by jasonwilliams** [comment] 2022-02-15 06:11
Could you provide some steps to reproduce?

**Comment by narliecholler** [comment] 2022-03-09 17:43
any update on this??

**Comment by DoroGi** [comment] 2022-03-11 17:49
I also had this issue. I tried debugging it a bit.

For me it breaks at the first getPage I try, on this line:
https://github.com/next-page-tester/next-page-tester/blob/4cea3f87801632f9f21644c2cad7efb15605cafe/src/nextConfig.ts#L37
The value of nextRoot is correct.

I have an extremely basic next.config.js
`module.exports = {
  basePath: '/pagine',
  reactStrictMode: true,
  poweredByHeader: false,
  serverRuntimeConfig: {},
  publicRuntimeConfig: {},
};
`

Next version: 12.0.7
next-page-tester: 0.31.0
running on IOS

Hope this helps!

**Comment by toomuchdesign** [comment] 2022-04-06 09:58
Closing since there's no repro and there's no way to ensure whether still relevant.

**Closed by toomuchdesign** 2022-04-06 09:58 UTC
Labels: needs-repro
